### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by maho24at** [yuyangchee98/F1-Points-Calculator#19]
Hi, 

thank you for this funny tool, I'm also racing in a karting series and I modified your calculator to fit it to our championship standings and racers, dont you want to make it a tool for championships where you can edit the number of races or games and the players or racers? 

I could help you a bit...

and I have a feature request, because we are a semi professional racing series we have 4 races that you can pass, basically every racer gets 4 results deleted so that you can miss 4 races during the season, so the worse 4 results on each racer will be deleted automatically, is there a chance you could include that? 

we "only" have 16 races - it took me a while to find the number of colums in the css file not in the code :P 

so if you want to make a fork of it here are some ideas for the settings page

- drivers / number / team / car brand (maybe a picture)
- random color to the driver / or fixed color for driver / team
- number of races (and names)
- points for results
- extra points (fastes lap e.g.)
- name of races or tracks
-  race results - so you can add the results without editing the code...

and some analysis for the points - and maybe a case prediction for the results of the last races with the outcome for the championship results or so.. 

its just an idea :)

**Comment by yuyangchee98** [comment]
Thanks.

I would be happy to modify the current project to generalize it so as to include the features you listed, as long as F1 points calculation still exists somewhere within it. Not sure if a fork is necessary at this time. 

I'll look into planning to implementing these features over time. If you have a PR, please submit it

**Comment by maho24at** [comment]
what do you mean with PR?

**Comment by yuyangchee98** [comment]
Pull request
